export default [
	{
		id: 1,
		company: 'Dixre Enterprise',
		position: 'Full stack Developer',
		type: 'Intern',
		duration: 'September 2017 - January 2019',
		location: 'Kaduna, Nigeria.',
	},
	{
		id: 2,
		company: 'STED Technologies',
		position: 'Frontend and Mobile Developer',
		type: 'Fulltime',
		duration: 'March 2019 - December 2021',
		location: 'Nigeria.',
	},
	{
		id: 3,
		company: 'Greysoft Technologies',
		position: 'Full stack Developer',
		type: 'Fulltime',
		duration: 'January 2022 - July 2022',
		location: 'Kaduna, Nigeria.',
	},
	{
		id: 4,
		company: 'Comuna',
		position: 'Full stack developer',
		type: 'Fulltime',
		duration: 'April 2022 - December 2022',
		location: 'Kaduna, Nigeria.',
	},
	{
		id: 5,
		company: 'Medical Identification',
		position: 'Frontend Lead',
		type: 'Fulltime',
		duration: 'August 2022 - Feb 2023',
		location: 'Kaduna, Nigeria.',
	},
	{
		id: 6,
		company: 'Vorbtech',
		position: 'React Native Developer',
		type: 'Contract',
		duration: 'Dev 2022 - Nov 2023',
		location: 'Abuja, Nigeria.',
	},
	{
		id: 7,
		company: 'Spectra Risk',
		position: 'Frontend Developer',
		type: 'Fulltime',
		duration: 'Nov 2023 - Present',
		location: 'Wilmington, Delaware. United States.',
	},
] as any[];
