export default [
	{
		id: 1,
		company: "Medical Identification",
		position: "Frontend Lead",
		type: "Fulltime",
		duration: "August 2022 - Present",
		location: "Kaduna, Nigeria.",
	},
	{
		id: 2,
		company: "Comuna",
		position: "Full stack developer",
		type: "Fulltime",
		duration: "April 2022 - December 2022",
		location: "Kaduna, Nigeria.",
	},
	{
		id: 3,
		company: "Greysoft Technologies",
		position: "Full stack Developer",
		type: "Fulltime",
		duration: "January 2022 - July 2022",
		location: "Kaduna, Nigeria.",
	},
	{
		id: 4,
		company: "STED Technologies",
		position: "Frontend and Mobile Developer",
		type: "Fulltime",
		duration: "March 2019 - December 2021",
		location: "Nigeria.",
	},
	{
		id: 5,
		company: "Dixre Enterprise",
		position: "Full stack Developer",
		type: "Intern",
		duration: "September 2017 - January 2019",
		location: "Kaduna, Nigeria.",
	},
] as any[];
